[env]
platform = espressif32
framework = arduino
upload_speed = 921600
lib_deps =
    mathertel/OneButton @ ^2.6.1

[env:blink]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<blink.cpp>
build_flags =
    -DLED_PIN=7
    -DLED_ACT=HIGH

[env:double_click]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<doubleClick.cpp>
build_flags =
    -DLED_PIN=7
    -DLED_ACT=HIGH
    -DBTN_PIN=0
    -DBTN_ACT=LOW

[env:2leds]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<2leds.cpp>
build_flags =
    -DLED_PIN_1=7
    -DLED_PIN_2=8
    -DLED_ACT=HIGH
    -DBTN_PIN=9
    -DBTN_ACT=LOW